title: Parker H. Holzer
logo: /assets/img/logo.jpeg
description: Department of Statistics & Data Science
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

parker.holzer@yale.edu
Department of Statistics & Data Science
Yale University
